name: Build Android release

on:
  push:
    tags:
     - '*'

env:
  RELEASE_ARCHIVE_NAME: android-release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: 
      image: rinekri/pjsip-android-builder:latest  # TODO: replace with intermedia image when it will be uploaded
      volumes:
        - ${{ github.workspace }}:/home/tools/pjproject 
        - ${{ github.workspace }}:/home/output/pjsip-build-output
      options: --user root
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Build library
        run: |
          cd /home
          ./build
      - 
        name: Create release asset 
        env: 
          PJSIP_OUTPUT_PATH: ${{ github.workspace }}/android
        run: |
          pwd
          ls $PJSIP_OUTPUT_PATH
          tar -czvf "$RELEASE_ARCHIVE_NAME".tar.gz -C "$PJSIP_OUTPUT_PATH" .
      - 
        name: Create release
        env:
          ASSET_PATH: ${{ github.workspace }}/${{ env.RELEASE_ARCHIVE_NAME }}
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Android release ${{ github.ref_name }}
          artifacts: ${{ env.ASSET_PATH }}.tar.gz
          draft: true
          prerelease: false
