name: Merge master to im-master PR

on:
  push:
    branches:
      feature/APPS-13617

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  SOURCE_BRANCH: "feature/APPS-13617"
  TARGET_BRANCH: "master"
  PR_TITLE: "Automated Pull Request"
  PR_BODY: "Merge $SOURCE_BRANCH to $TARGET_BRANCH"
  REVIEWERS: "dshamaev-intermedia"

jobs:
  master_to_im_master_pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0

    - name: Create Pull Request
      id: create_pr
      run: |
        response=$(curl -v -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          https://api.github.com/repos/$REPO_NAME/pulls \
          -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$SOURCE_BRANCH\",\"base\":\"$TARGET_BRANCH\"}")

        pr_number=$(echo "$response" | jq -r '.number')
        if [ "$pr_number" ]; then
          echo "Pull request created successfully. PR NUMBER: $pr_number"
        else
          echo "Failed to create pull request. HTTP status: $response"
          exit 1
        fi

    - name: Add Reviewers
      if: success()
      run: |
        PR_NUMBER=$(echo ${{ steps.create_pr.outputs.pr_number }})

        curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/requested_reviewers \
          -d "{\"reviewers\":[\"$REVIEWERS\"]}"