name: Merge master to im-master PR

on:
  push:
    branches:
      feature/APPS-13617

jobs:
  master_to_im_master_pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0

    - name: Create Pull Request
      run: |
        TOKEN=${{ github.token }}
        REPO_NAME=${{ github.repository }}
        SOURCE_BRANCH="feature/APPS-13617"
        TARGET_BRANCH="master"
        PR_TITLE="Automated Pull Request"
        PR_BODY="This pull request was automatically created by a GitHub Actions workflow."

        echo "$SOURCE_BRANCH"
        echo "$TARGET_BRANCH"

        response=$(curl -v -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          https://api.github.com/repos/$REPO_NAME/pulls \
          -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"feature/APPS-13617\",\"base\":\"master\"}")

        pr_number=$(echo "$response" | jq -r '.number')

        echo "PR NUMBER: $pr_number"