name: Merge master to im-master PR

on:
  push:
    branches:
      feature/APPS-13617

jobs:
  master_to_im_master_pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: my-im-master
        fetch-depth: 0

    - name: Create Pull Request
      run: |
        TOKEN=${{ github.token }}
        REPO_NAME=${{ github.repository }}
        SOURCE_BRANCH=master
        TARGET_BRANCH=my-im-master
        PR_TITLE="Automated Pull Request"
        PR_BODY="This pull request was automatically created by a GitHub Actions workflow."

        curl -v -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO_NAME/pulls \
          -d '{"title":"$PR_TITLE","body":"$PR_BODY","head":"$SOURCE_BRANCH","base":"$TARGET_BRANCH"}'

        pr_number=$(echo "$response" | jq -r '.number')

        echo "PULL REQUEST NUMBER: $pr_number"