name: Merge master to im-master PR

on:
  push:
    branches:
      feature/APPS-13617

jobs:
  master_to_im_master_pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0

    - name: Create Pull Request
      run: |
        TOKEN=${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER=${{ github.repository_owner }}
        REPO_NAME=${{ github.repository }}

        SOURCE_BRANCH=master
        
        TARGET_BRANCH=im-master

        PR_TITLE="Automated Pull Request"
        PR_BODY="This pull request was automatically created by a GitHub Actions workflow."

        curl -X POST \
          -H "Authorization: token $TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls \
          -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$SOURCE_BRANCH\",\"base\":\"$TARGET_BRANCH\"}"