name: Update Master

on:
  push:
    branches: [feature/APPS-13617]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up upstream
        run: |
          if ! git remote | grep -q "upstream"; then
            git remote add upstream https://github.com/pjsip/pjproject.git
          fi
      
      - name: Fetch upstream
        run: git fetch upstream

      - name: Configure git
        run: |
          git config user.name "CI Bot"
          git config user.email "noreply@myemail.com"

      - name: Merge upstream/master into master
        run: |
          if git merge upstream/master; then
            echo ""
            SLACK_MESSAGE="Update Master workflow executed successfully."
            curl -X POST --data-urlencode "payload={\"channel\": \"#unite-mobile-pjproject\", \"username\": \"ci-bot\", \"text\": \":azure-check-mark: *Merge upstream/master to master* successful! <https://github.com/intermedia-net/pjproject/actions/workflows/update-master.yml|Click here> for details! \", \"icon_emoji\": \":unite:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          else
            echo "Merge conflict detected!"
            SLACK_MESSAGE="Merge conflict detected in the Update Master workflow!"
            curl -X POST --data-urlencode "payload={\"channel\": \"#unite-mobile-pjproject\", \"username\": \"ci-bot\", \"text\": \":azure-x-mark: *Upstream/master to master merge* conflict detected! <https://github.com/intermedia-net/pjproject/actions/workflows/update-master.yml|Click here> for details! \", \"icon_emoji\": \":unite:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
            exit 1
          fi

      - name: Push changes
        run: git push origin master        